[gdrive]
file_id = "1BKBON9lIY3nI-VR3253jDCXyAMbbH0jw"
auto_backup = false

service_account_json = """
{
  "type": "service_account",
  "project_id": "payroll-app-471704",
  "private_key_id": "c1fff47a8433b0284a89454d09e6066df0a0de4b",
  private_key = """
-----BEGIN PRIVATE KEY-----
\nMIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQCg/iVZwH4NXAiI\n8W+mozXbOcLHtckCD6jdxHmAI7q/qK9OohJYY0NDmWMycuEWrFAfUpAsaKvAiotX\nfk5JckfKYRHnTWoQqBk+a4g4Z+ozZOg9pWnCVMTbPyRgaCFkO3BqPXp9zq1+6yvm\nAlhAseculOwhv9KICWL5nJgSfZI1UQWam0cpwz1tBOzL2/Ii8gBxnv4tbR+7SA+k\nYdTRSN9wa+XkwPgiPkPBACN40kxIuMUrhNyR1ZqF7sV56AUZAFSrv2/SL7pdh5iW\nRL5vzvMUO/tASQ2ApxPTGjSc46w/VJXyq0RyHZUIIa+phBFhIyeYQfBmYTAsEvW+\nhZfSl5OFAgMBAAECgf81S+2RiOgyBAXPUB5mTCHIMZcKBmRFCmodAK44fZuVV4Kx\nxXXNTQ83kdAFI4LgvqrHs82G5h/13efDT00bg3nAxeHncPlsCjpRL8go5D3kRcOc\npOYeL3H8Iysnv1FOnV7ZzQCAJavKGJCv1Jbi1AJ0qViC074eyvy5Jd4yQN/mRiV1\nzrckJN33B5UfpiVzmsi5IL4FkFPO0KdEPr7ttC/REl8dWqEVpsfngibVE22Lzdej\nl0AIY91v/kMLOqxrQlsfadAkmAQJkxtTwk6yBeGqp9TwrrNfKeqYGNtM9Bjf0l1f\n8f3UzEF7T4tvdGD68n6XnmDslAjal+cm6jSaN+ECgYEA3GgDR97JWdLYMeOFahTc\nIg1X0U6v+F4QTOWE0YrhycxFpS1e5VUA7+VlmOSAJpE9Qg7ngRAD+HcMNq8dvZF+\nJlPuhPx75QAW5YV2gqeWnwKu7zIb3ypymOBYiFHNmGRPzjdP0Cq9PhTF0KilL4IV\nDK43z96WoTxcyfKLWC0PjaECgYEAuv3fNRB/hySueYAucptMSKJ3nC6d5IraPNXT\nKII2Z+RP+Sr/KmWwhMZXKaUAjxIoBq6QGW9Fe0+AiiYxFHxiY4+jzTalAYXyJubs\nCJGbBbbRxYk5l+VXGkOEp1DyI3qaVd0ogcqn0TKXcwbqBAzj5GxXPdo79RaX8anK\nWUUZ02UCgYEAzKFNGnb/XgPhcUAZ58mCL6NPuyZhPiim3Z3iWGGnC6I5rweWqTjo\na9IBJ5hOWoBR7XjE+xCRfyeYEVU4OX5RLuiR9KotpQkWOPZWdyt9LhhhrfZJ5kIU\nr1brG3VHeor3hS/ZTB3CIVdL6VQKOTd+r404iCfSldPjGiOzt6PuYsECgYBvQ6iR\nFqQLchQvT8pTf3zAq4uob0ScPNLm6AShUfm1j/DWPnNecuu51Zr/uKLAfvk6IJy1\nxbP+T6wYh+kkW27f9xRsg1tjsKQJ6dYAs0Me/02K0MBoVZqikhJYzJ2H5uf2t4Xm\n1QNOQ2BCnZaZmmHwBVdUAosypqL6tSEmRSu80QKBgQDTZkDjA6YDSXjLE72RLDK1\nf9G6RHOKKNVZVRtvIIM1aQvsUbcbhyZyU3ZdllSJmrdsbssgXybhTW3mSO1Rso/l\n8DbDbhlrZxj/o976hWKtHPZsukOjsATxiounIqdVod2+iW0w19aigzD26pfbpZLv\nXxe1QgjwCv+WsHYB30EuMw==\n
-----END PRIVATE KEY-----
"""
  "client_email": "payroll-service@payroll-app-471704.iam.gserviceaccount.com",
  "client_id": "102342577944254367185",
  "auth_uri": "https://accounts.google.com/o/oauth2/auth",
  "token_uri": "https://oauth2.googleapis.com/token",
  "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
  "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/payroll-service%40payroll-app-471704.iam.gserviceaccount.com"
}
"""
