[gdrive]
file_id = "YOUR_DRIVE_FILE_ID"

# Paste your entire service account JSON here:
service_account_json = """
{
  "type": "service_account",
  "project_id": "your-project-id",
  "private_key_id": "XXXX",
  "private_key": "-----BEGIN PRIVATE KEY-----\n....\n-----END PRIVATE KEY-----\n",
  "client_email": "your-service-account@your-project.iam.gserviceaccount.com",
  "client_id": "XXXX",
  ...
}
"""
